# build with context from root of source tree
FROM node:lts AS build
WORKDIR /app
COPY ./ui /app
RUN corepack enable && yarn set version berry
RUN git config --global url."https://github".insteadOf ssh://git@github && \
    git config --global url."https://github.com/".insteadOf git@github.com:
RUN yarn install
RUN yarn run build



FROM nginx:trixie AS server
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./ui/nginx.conf /etc/nginx/nginx.conf

# docker build args
ARG BUILD_VERSION
ENV VERSION=${BUILD_VERSION}
RUN echo "{\"version\":\"${VERSION}\"}" > /usr/share/nginx/html/version.json

EXPOSE 80